#spring.datasource.url=jdbc:mysql://localhost:3306/learn?useSSL=false
#
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn?useSSL=false
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
